services:
  back-app:
    build:
      context: ./backend
      dockerfile: dockerfiles/php/Dockerfile
    image: back-app
    container_name: back-app
    tty: true
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/var/www
    networks:
      - laravel_app

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www
      - ./backend/dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_app

networks:
  laravel_app:
    driver: bridge
